export const ConnectionsPage = {
  heading: 'text=API Connections',
  subheading: 'text=Manage API keys for external services',
  btnAddType: 'button:has-text("Add Type")',
  btnAddConnection: 'button:has-text("Add Connection")',
  createModalHeading: 'text=New Connection',
  createNameInput: 'input[placeholder="My Weather API"]',
  createProviderSelect: 'select:has(option:has-text("OpenWeatherMap"))',
  createApiKeyInput: 'input[placeholder="e.g., sk-1234567890abcdef"]',
  createSubmitBtn: 'button:has-text("Create")',
  createCancelBtn: 'button:has-text("Cancel")',
  editModalHeading: 'text=Edit Connection',
  editSaveBtn: 'button:has-text("Save")',
  deleteConfirmModal: 'text=Confirm Delete',
  deleteConfirmBtn: 'button:has-text("Delete")',
  deleteCancelBtn: 'button:has-text("Cancel")',
  connectionTable: '[data-testid="connection-table"]',
  providerBadge: '.rounded-full.text-xs.font-medium',
  emptyState: 'text=No connections yet',
  customTypeModalHeading: 'text=Add Connection Type',
  customTypeNameInput: 'input[placeholder="e.g., OpenWeatherMap"]',
  customTypeIdInput: 'input[placeholder="e.g., openweather"]',
  customTypeCategoryInput: 'input[placeholder="e.g., Weather"]',
  customTypeSubmitBtn: 'button:has-text("Add Type")',
  toggleKeyVisibility: 'button[title="Show key"], button[title="Hide key"]',
  btnEdit: 'button[title="Edit"]',
  btnDelete: 'button[title="Delete"]',
  totalLabel: 'text=Total:',
  errorClass: '.text-red-600',
};
