export const EditorPage = {
  toolbar: '[data-testid="toolbar"]',
  btnSave: '[data-testid="btn-save"]',
  btnPushLive: '[data-testid="btn-push-live"]',
  btnUndo: '[data-testid="btn-undo"]',
  btnRedo: '[data-testid="btn-redo"]',
  btnDeleteModule: '[data-testid="btn-delete-module"]',
  btnDevicePicker: '[data-testid="btn-device-picker"]',
  structureTree: '[data-testid="structure-tree"]',
  btnAddRow: '[data-testid="btn-add-row"]',
  canvas: '[data-testid="editor-canvas"]',
  propertyInspector: '[data-testid="property-inspector"]',
  selectVariant: '[data-testid="select-variant"]',
  toggleShowDivider: '[data-testid="toggle-show-divider"]',
  btnTemplates: 'button:has-text("Templates")',
  btnSaveAsTemplate: 'button:has-text("Save as Template")',
  btnPreviewApp: 'button:has-text("Preview App")',
  unknownLabel: 'text=Unknown',
};
