export const TemplatesPage = {
  heading: 'text=Templates',
  btnPreviewWholeApp: 'button:has-text("Preview Whole App")',
  btnOpenEditor: 'button:has-text("Open Editor")',
  searchInput: 'input[placeholder="Search templates..."]',
  categoryFilter: 'select:has(option:has-text("All categories"))',
  templateCards: '[data-testid="template-card"]',
  btnPreview: 'button[title="Preview"]',
  btnApply: 'button[title="Apply to module"]',
  btnDelete: 'button[title="Delete"]',
  previewModal: 'text=Preview',
  previewJsonToggle: 'button.font-mono',
  previewClose: 'button:has-text("Close")',
  previewApplyToModule: 'button:has-text("Apply to Module")',
  applyModal: '[data-testid="template-apply-modal"]',
  applyModalHeading: 'text=Apply Template',
  applyVersionSelect: '[data-testid="template-version-select"]',
  applyTargetExisting: '[data-testid="template-target-existing"]',
  applyTargetNew: '[data-testid="template-target-new"]',
  applyModuleSelect: '[data-testid="template-module-select"]',
  applyAutoCheckpoint: '[data-testid="template-auto-checkpoint"]',
  applyAsDraftBtn: '[data-testid="template-apply-submit"]',
  applyCancelBtn: '[data-testid="template-apply-cancel"]',
  loadingMsg: 'text=Loading templates...',
  emptyMsg: 'text=No templates found. Create one from the Module Editor.',
  categoryBadge: '.rounded-full.text-xs.font-medium',
  publicBadge: 'text=Public',
};
