export const TemplatesPage = {
  heading: 'text=Templates',
  btnPreviewWholeApp: 'button:has-text("Preview Whole App")',
  btnOpenEditor: 'button:has-text("Open Editor")',
  searchInput: 'input[placeholder="Search templates..."]',
  categoryFilter: 'select:has(option:has-text("All categories"))',
  templateCards: '[data-testid="template-card"]',
  btnPreview: 'button[title="Preview"]',
  btnApply: 'button[title="Apply to module"]',
  btnDelete: 'button[title="Delete"]',
  previewModal: 'text=Preview',
  previewJsonToggle: 'button.font-mono',
  previewClose: 'button:has-text("Close")',
  previewApplyToModule: 'button:has-text("Apply to Module")',
  applyModalHeading: 'text=Apply Template',
  applyModuleSelect: 'select:has(option:has-text("Select a module..."))',
  applyAsDraftBtn: 'button:has-text("Apply as Draft")',
  applyCancelBtn: 'button:has-text("Cancel")',
  loadingMsg: 'text=Loading templates...',
  emptyMsg: 'text=No templates found. Create one from the Module Editor.',
  categoryBadge: '.rounded-full.text-xs.font-medium',
  publicBadge: 'text=Public',
};
