export const WorkflowsPage = {
  heading: 'h1:text-is("Workflows")',
  workflowList: 'div:has-text("Your Workflows")',
  workflowListItems: '.divide-y > div.cursor-pointer',
  btnNewWorkflow: 'button:has-text("New Workflow")',
  btnImportN8n: 'button:has-text("Import n8n")',
  btnSave: 'button:has-text("Save")',
  btnExecute: 'button:has-text("Execute")',
  createModal: 'text=Create Workflow',
  createNameInput: 'input[placeholder="My Workflow"]',
  createDescInput: 'textarea[placeholder="Optional description"]',
  createTriggerSelect: 'select:has(option:has-text("Manual"))',
  createCreateBtn: 'button:has-text("Create")',
  createCancelBtn: 'button:has-text("Cancel")',
  importModal: 'text=Import n8n Workflow',
  importJsonInput: 'textarea[placeholder="Paste n8n workflow JSON here..."]',
  importImportBtn: 'button:has-text("Import")',
  addNodeTrigger: 'button:has-text("+ Trigger")',
  addNodeAction: 'button:has-text("+ Action")',
  addNodeCondition: 'button:has-text("+ Condition")',
  addNodeSwitch: 'button:has-text("+ Switch")',
  addNodeLoop: 'button:has-text("+ Loop")',
  nodeInspector: '.bg-white:has-text("Delete")',
  emptyState: 'text=Select a workflow or create a new one',
  deleteBtn: 'button:has-text("Delete")',
  noWorkflowsMsg: 'text=No workflows yet. Create one to get started.',
};
