"""add sandbox_actions table

Revision ID: 089ea87bcf18
Revises: 1d07216a865d
Create Date: 2026-04-06 00:38:39.774958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '089ea87bcf18'
down_revision: Union[str, None] = '1d07216a865d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request_body', sqlite.JSON(), nullable=True),
    sa.Column('response_body', sqlite.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandbox_actions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_actions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandbox_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_actions_session_id'))

    op.drop_table('sandbox_actions')
    # ### end Alembic commands ###
