"""add_unique_constraint_user_id_module_type_on_module_states

Revision ID: 12d257e0ec5e
Revises: 089ea87bcf18
Create Date: 2026-04-11 23:00:17.578880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12d257e0ec5e'
down_revision: Union[str, None] = '089ea87bcf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Deduplicate rows before adding the unique constraint.
    # Keep the row with the highest version (most recent data) per (user_id, module_type).
    conn = op.get_bind()
    conn.execute(sa.text("""
        DELETE FROM module_states
        WHERE id NOT IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY user_id, module_type
                           ORDER BY version DESC, updated_at DESC
                       ) AS rn
                FROM module_states
            ) ranked
            WHERE rn = 1
        )
    """))

    with op.batch_alter_table('module_states', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_module_states_user_type', ['user_id', 'module_type'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_states', schema=None) as batch_op:
        batch_op.drop_constraint('uq_module_states_user_type', type_='unique')

    # ### end Alembic commands ###
