"""add sdui_templates and sdui_screen_history tables

Revision ID: 1d07216a865d
Revises: 31969323f95b
Create Date: 2026-04-06 00:30:49.718974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d07216a865d'
down_revision: Union[str, None] = '31969323f95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdui_screen_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('screen_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sdui_screen_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sdui_screen_history_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sdui_screen_history_user_id'), ['user_id'], unique=False)

    op.create_table('sdui_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('screen_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sdui_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sdui_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sdui_templates_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdui_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sdui_templates_created_by'))
        batch_op.drop_index(batch_op.f('ix_sdui_templates_category'))

    op.drop_table('sdui_templates')
    with op.batch_alter_table('sdui_screen_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sdui_screen_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_sdui_screen_history_module_id'))

    op.drop_table('sdui_screen_history')
    # ### end Alembic commands ###
