"""add component_registry table

Revision ID: 31969323f95b
Revises: 644530918c51
Create Date: 2026-04-06 00:24:59.915967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31969323f95b'
down_revision: Union[str, None] = '644530918c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('props_schema', sa.JSON(), nullable=False),
    sa.Column('default_props', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_registry_type'), ['type'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_registry_type'))

    op.drop_table('component_registry')
    # ### end Alembic commands ###
