"""ff4_app_template_versioning

Revision ID: 5468f59c7834
Revises: 59b20307e798
Create Date: 2026-05-14 13:03:13.222005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5468f59c7834'
down_revision: Union[str, None] = '59b20307e798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('default_timestamp_name', sa.String(length=255), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('template_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['sdui_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_versions_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_versions_user_id'), ['user_id'], unique=False)

    op.create_table('app_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('default_timestamp_name', sa.String(length=255), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('resolved_module_versions', sa.JSON(), nullable=False),
    sa.Column('module_reference_policies', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('min_mobile_runtime_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_versions_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_versions_user_id'), ['user_id'], unique=False)

    op.create_table('app_working_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('last_autosaved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_version_id', sa.String(length=36), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_working_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_working_drafts_app_id'), ['app_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_working_drafts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sdui_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_version_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdui_templates', schema=None) as batch_op:
        batch_op.drop_column('current_version_id')

    with op.batch_alter_table('app_working_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_working_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_working_drafts_app_id'))

    op.drop_table('app_working_drafts')
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_versions_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_versions_app_id'))

    op.drop_table('app_versions')
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_versions_user_id'))
        batch_op.drop_index(batch_op.f('ix_template_versions_template_id'))

    op.drop_table('template_versions')
    # ### end Alembic commands ###
