"""add_session10_models

Revision ID: 5f1877f37748
Revises: d15c43b2c823
Create Date: 2026-04-24 15:10:56.344341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f1877f37748'
down_revision: Union[str, None] = 'd15c43b2c823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('splash', sa.Text(), nullable=True),
    sa.Column('theme', sa.JSON(), nullable=False),
    sa.Column('design_tokens', sa.JSON(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('default_launch_module_id', sa.String(length=36), nullable=True),
    sa.Column('bottom_bar_config', sa.JSON(), nullable=False),
    sa.Column('launchpad_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_launch_module_id'], ['module_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_default_launch_module_id'), ['default_launch_module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_user_id'), ['user_id'], unique=False)

    op.create_table('app_module_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('module_instance_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('slot_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_module_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_module_refs_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_module_refs_module_instance_id'), ['module_instance_id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_app_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_assigned_app_id'), ['assigned_app_id'], unique=False)
        batch_op.create_foreign_key('fk_devices_assigned_app_id', 'apps', ['assigned_app_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devices_assigned_app_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_devices_assigned_app_id'))
        batch_op.drop_column('assigned_app_id')

    with op.batch_alter_table('app_module_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_module_refs_module_instance_id'))
        batch_op.drop_index(batch_op.f('ix_app_module_refs_app_id'))

    op.drop_table('app_module_refs')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_user_id'))
        batch_op.drop_index(batch_op.f('ix_apps_default_launch_module_id'))

    op.drop_table('apps')
    # ### end Alembic commands ###
