"""Update workflow model for React Flow

Revision ID: 97967c8d628b
Revises: 0b3ecd975b0f
Create Date: 2026-04-17 12:00:18.712497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '97967c8d628b'
down_revision: Union[str, None] = '0b3ecd975b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add new columns with nullable=True temporarily
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('trigger_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=False)

    # Step 2: Migrate existing data
    # Convert old action_config to new graph format
    connection = op.get_bind()
    workflows = connection.execute(sa.text("SELECT id, action_config, is_active FROM workflows")).fetchall()

    for workflow_id, action_config_json, is_active in workflows:
        import json

        # Parse old action_config
        action_config = json.loads(action_config_json) if action_config_json else {}

        # Build new graph structure for React Flow
        # Old format: {"actions": [{"type": "...", "params": {...}}]}
        # New format: {"nodes": [...], "edges": [...]}
        nodes = []
        edges = []

        actions = action_config.get('actions', [])
        for idx, action in enumerate(actions):
            node_id = f"node-{idx}"
            nodes.append({
                "id": node_id,
                "type": "action",
                "position": {"x": 100, "y": 100 + (idx * 100)},
                "data": {
                    "label": action.get('type', 'unknown'),
                    "actionType": action.get('type'),
                    "params": action.get('params', {})
                }
            })

            # Connect sequential nodes
            if idx > 0:
                edges.append({
                    "id": f"edge-{idx-1}-{idx}",
                    "source": f"node-{idx-1}",
                    "target": node_id,
                    "type": "default"
                })

        graph = {"nodes": nodes, "edges": edges}

        # Update the row
        connection.execute(
            sa.text("UPDATE workflows SET graph = :graph, enabled = :enabled WHERE id = :id"),
            {"graph": json.dumps(graph), "enabled": bool(is_active), "id": workflow_id}
        )

    # Step 3: Make columns non-nullable and drop old columns
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('graph', nullable=False)
        batch_op.alter_column('enabled', nullable=False)
        batch_op.drop_column('action_config')
        batch_op.drop_column('run_count')
        batch_op.drop_column('last_run_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('last_run_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('run_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('action_config', sqlite.JSON(), nullable=False))
        batch_op.alter_column('trigger_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('enabled')
        batch_op.drop_column('graph')

    # ### end Alembic commands ###
