"""add_last_active_to_sessions

Revision ID: ace0bc925c39
Revises: f3a1b2c4d5e6
Create Date: 2026-04-21 09:34:34.121353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ace0bc925c39'
down_revision: Union[str, None] = 'f3a1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if conversations table exists before trying to drop it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'conversations' in tables:
        with op.batch_alter_table('conversations', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        op.drop_table('conversations')

    # Check if conversation_id column exists before trying to drop it
    if 'chat_messages' in tables:
        columns = [col['name'] for col in inspector.get_columns('chat_messages')]
        if 'conversation_id' in columns:
            with op.batch_alter_table('chat_messages', schema=None) as batch_op:
                batch_op.drop_column('conversation_id')

    # Check if last_active already exists before adding it
    if 'sessions' in tables:
        columns = [col['name'] for col in inspector.get_columns('sessions')]
        if 'last_active' not in columns:
            with op.batch_alter_table('sessions', schema=None) as batch_op:
                batch_op.add_column(sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('last_active')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=True))

    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("'New Chat'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
