"""add_run_count_and_last_run_at_to_workflows

Revision ID: d4aa5857b012
Revises: de71aeb133e3
Create Date: 2026-03-23 20:22:51.413404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4aa5857b012'
down_revision: Union[str, None] = 'de71aeb133e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('last_run_at')
        batch_op.drop_column('run_count')

    # ### end Alembic commands ###
