"""Add device_error_reports table and module_version status

Revision ID: d8dc2a68d143
Revises: 0a1b2c3d4e5f
Create Date: 2026-05-16 12:44:51.502843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd8dc2a68d143'
down_revision: Union[str, None] = '0a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_error_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('preview_session_id', sa.String(length=36), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_error_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_error_reports_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_error_reports_preview_session_id'), ['preview_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_error_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('module_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'active'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_versions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('device_error_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_error_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_error_reports_preview_session_id'))
        batch_op.drop_index(batch_op.f('ix_device_error_reports_device_id'))

    op.drop_table('device_error_reports')
    # ### end Alembic commands ###
