"""add_temperature_max_tokens_is_active_to_agent_configs

Revision ID: ee17096d9496
Revises: d4aa5857b012
Create Date: 2026-03-26 10:38:00.093716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee17096d9496'
down_revision: Union[str, None] = 'd4aa5857b012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('max_tokens')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
